### ISSUE TITLE
NFException for track numbers formatted like 1/10

### ISSUE THREAD

**Issue by massdosage** [massdosage/mass-scrobblage#1]
Exception in thread "main" java.lang.NumberFormatException: For input string: "1/10"
        at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
        at java.lang.Integer.parseInt(Integer.java:580)
        at java.lang.Integer.valueOf(Integer.java:766)
        at za.co.massdosage.scrobble.FileScrobbler.extractScrobble(FileScrobbler.java:152)
        at za.co.massdosage.scrobble.FileScrobbler.extractScrobbles(FileScrobbler.java:123)
        at za.co.massdosage.scrobble.FileScrobbler.extractScrobbles(FileScrobbler.java:113)
        at za.co.massdosage.scrobble.FileScrobbler.scrobbleFolder(FileScrobbler.java:87)
        at za.co.massdosage.scrobble.MassScrobblage.main(MassScrobblage.java:83)

**Comment by massdosage** [comment]
Fixed in 1.0.1
